

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${ENV_PROTUBE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ENV_PROTUBE_DB_PWD:-secret}
      POSTGRES_DB: ${ENV_PROTUBE_DB:-protube}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
